version: "3.9"
services:
  coaching-platform-pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "med-catalog"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
